# dateformat: MM/dd/yy hh:mma zzz
# Date Variables:
# Variable, Name, Example
# G	Era designator,	AD
# y	Year,	1996; 96
# M	Month in year,	July; Jul; 07
# w	Week in year,	27
# W	Week in month,	2
# D	Day in year,	189
# d	Day in month,	10
# F	Day of week in month,	2
# E	Day in week,	Tuesday; Tue
# a	Am/pm marker,	PM
# H	Hour in day (0-23),	0
# k	Hour in day (1-24),	24
# K	Hour in am/pm (0-11),	0
# h	Hour in am/pm (1-12),	12
# m	Minute in hour,	30
# s	Second in minute,	55
# S	Millisecond,	978
# z	Time zone	General time zone	Pacific Standard Time; PST; GMT-08:00
# Z	Time zone	RFC 822 time zone	-0800
# 
#
# universal_mailboxes: false
# Right-click any mailbox to open your own mailbox if true, otherwise you must click your own
# 
# attachments: false
# Not yet implemented, ability to add attachments to books when mailing
# 
# login_notifications: true
# Notify players if they have mail on login
dateformat: MM/dd/yy hh:mma zzz
universal_mailboxes: false
attachments: false
login_notification: true
mailbox_rows: 4
max_attachments: 4