name: RealMail
description: Send mail to physical mailboxes without commands
version: 0.1.1
author: Ben Sergent V

main: com.challengercity.plugins.realmail.RealMail
database: false
#depend: [WorldEdit]

permissions:
  realmail.user.*:
    description: Access to personal mailboxes
    default: true
    children:
      realmail.user.setmailbox: true
      realmail.user.sendmail: true
      realmail.user.delmailbox: true
      realmail.user.clear: true
  realmail.admin.*:
    description: Access to commands like bulk-mailing
    default: op
    children:
      realmail.admin.bulkmail: true
      realmail.admin.setmailbox.others: true
      realmail.admin.delmailbox.others: true