name: RealMail
description: Send mail to physical mailboxes without commands
version: 0.2.2
author: Ben Sergent V

main: com.challengercity.plugins.realmail.RealMail
database: false
#depend: [WorldEdit]

permissions:
  realmail.user.*:
    description: Access to personal mailboxes
    default: true
    children:
      realmail.user.sendmail: true
      realmail.user.attach: true
      realmail.user.craft.*:
        description: Access to crafting recipes
        default: true
        children:
          realmail.user.craft.mailbox: true
          realmail.user.craft.stationary: true
  realmail.admin.*:
    description: Access to commands like bulk-mailing
    default: op
    children:
      realmail.admin.bulkmail: true
      realmail.admin.bypassAttachmentLimits: true
      realmail.admin.instantDelivery: true
      
commands:
  mail:
    description: Shows usage information for RealMail